# Generated by Django 6.0.2 on 2026-05-12 00:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_cliente', models.CharField(choices=[('detalle', 'Detal'), ('vip', 'VIP'), ('mayorista', 'Mayorista'), ('distribuidor', 'Distribuidor')], default='detalle', max_length=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_pedidos', models.IntegerField(default=0)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_nit', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente_ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('es_credito', models.BooleanField(default=False)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('aplica_iva', models.BooleanField(default=False)),
                ('es_retenedor', models.BooleanField(default=False)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tipo_envio', models.CharField(choices=[('recogida', 'Recogida en tienda'), ('domicilio', 'Domicilio'), ('transportadora', 'Transportadora')], default='recogida', max_length=20)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='productos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('color_primario', models.CharField(default='#28a745', max_length=7)),
                ('color_secundario', models.CharField(default='#000000', max_length=7)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email_empresa', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=150, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIT')),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('pro', 'Pro'), ('premium', 'Premium')], default='basico', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('plan_vence', models.DateField(default=django.utils.timezone.localdate)),
                ('color_principal', models.CharField(default='#000000', max_length=20, verbose_name='Color principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('descripcion', models.TextField()),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('talla', models.CharField(blank=True, max_length=50, null=True)),
                ('colores_disponibles', models.JSONField(blank=True, default=list)),
                ('tallas_disponibles', models.JSONField(blank=True, default=list)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='productos/videos/')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('tipo_venta', models.CharField(choices=[('unidad', 'Por unidad'), ('gramo', 'Por gramos')], default='unidad', max_length=20)),
                ('peso_producto', models.DecimalField(blank=True, decimal_places=2, help_text='Peso del producto en gramos', max_digits=6, null=True)),
                ('precio_detal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_semimayor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_mayor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_mayorista', models.IntegerField(default=6)),
                ('precio_por_gramo_detal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_por_gramo_semimayor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_por_gramo_mayor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('talla', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retefuente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productovariante')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('session_key', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('talla', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productovariante')),
            ],
        ),
    ]
