# Generated by Django 6.0.5 on 2026-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pedido_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('vencido', 'Vencido')], default='pendiente', max_length=20),
        ),
    ]
