# Generated by Django 6.0.5 on 2026-05-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
