# Generated by Django 6.0.5 on 2026-05-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_perfil_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
