# Generated by Django 6.0.5 on 2026-05-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_perfil_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner_texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='color_primario',
            field=models.CharField(default='#122216', max_length=7),
        ),
    ]
