# Generated by Django 6.0.5 on 2026-06-05 23:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_perfil_banner_texto_alter_perfil_color_primario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
