# Generated by Django 6.0.5 on 2026-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'color', 'talla')},
        ),
    ]
