# Generated by Django 6.0.5 on 2026-06-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_producto_referencia_alter_producto_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='total_gramos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
