# Generated by Django 6.0.5 on 2026-06-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_pedidoitem_total_gramos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productovariante'),
        ),
    ]
