# Generated by Django 6.0.5 on 2026-06-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_alter_productoimagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
