# Generated by Django 6.0.5 on 2026-07-01 17:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_cliente_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='costo_envio_estandar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de Envío'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mercadopago_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago Access Token'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='wompi_public_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wompi Public Key'),
        ),
    ]
