# Generated by Django 6.0.5 on 2026-07-03 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_perfil_costo_envio_estandar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='webhook_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Webhook UUID'),
        ),
    ]
