# Generated by Django 6.0.5 on 2026-07-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_perfil_webhook_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pago Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción Wompi'),
        ),
    ]
