# Generated by Django 6.0.5 on 2026-07-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_pedido_mercadopago_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(default='fijo', max_length=50),
        ),
    ]
