# Generated by Django 6.0.5 on 2026-07-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_gasto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
