# Generated by Django 6.0.5 on 2026-07-08 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_alter_gasto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='acepta_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='categoria_favorita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_sin_comprar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Activo', 'Activo'), ('Frecuente', 'Frecuente'), ('VIP', 'VIP'), ('Inactivo', 'Inactivo')], default='Nuevo', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='etiquetas',
            field=models.CharField(blank=True, help_text='Ej: Novias, Mayorista, Plata', max_length=300),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_cumpleanos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel',
            field=models.CharField(choices=[('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Diamante', 'Diamante')], default='Bronce', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origen',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Tienda', 'Tienda'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('TikTok', 'TikTok'), ('Página Web', 'Página Web')], default='WhatsApp', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='proxima_tarea',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_factura',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_variante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_contacto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='variante_favorita_resumen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
