# Generated by Django 6.0.5 on 2026-07-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_alter_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
