# Generated by Django 6.0.5 on 2026-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_gasto_activo_gasto_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
