# Generated by Django 6.0.5 on 2026-07-10 00:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_productovariante_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_variante'),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
