# Generated by Django 6.0.5 on 2026-07-10 19:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_productovariante_activo_productovariante_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aplicar_descuentos',
            field=models.BooleanField(default=False, verbose_name='Activar Descuentos por Campaña / Temporada'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cobrar_envio',
            field=models.BooleanField(default=False, verbose_name='¿Cobrar Envío?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='consecutivo_actual',
            field=models.IntegerField(default=1, verbose_name='Siguiente Consecutivo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='envio_gratis_desde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Envío Gratis desde Monto'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='integracion_siigo_activa',
            field=models.BooleanField(default=False, verbose_name='Activar Sincronización con Siigo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mostrar_iva_discriminado',
            field=models.BooleanField(default=True, verbose_name='Mostrar IVA Discriminado en Factura'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='porcentaje_descuento_promo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje Descuento Promoción (%)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='Porcentaje de IVA (%)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prefijo_factura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo de Facturación'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='resolucion_dian',
            field=models.TextField(blank=True, null=True, verbose_name='Resolución DIAN'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='responsable_iva',
            field=models.BooleanField(default=False, verbose_name='¿Es Responsable de IVA?'),
        ),
    ]
