# Generated by Django 6.0.5 on 2026-07-15 16:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_perfil_aplicar_descuentos_perfil_cobrar_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_iva', models.BooleanField(default=False)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('mostrar_iva_discriminado', models.BooleanField(default=False)),
                ('es_retenedor', models.BooleanField(default=False)),
                ('porcentaje_retefuente', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Porcentaje de retención en la fuente (ej. 2.50 o 3.50)', max_digits=5)),
                ('cobrar_envio', models.BooleanField(default=False)),
                ('costo_envio_estandar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('envio_gratis_desde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('aplicar_descuentos', models.BooleanField(default=False)),
                ('porcentaje_descuento_promo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_fiscal', to='productos.perfil')),
            ],
        ),
    ]
