# Generated by Django 6.0.5 on 2026-07-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0027_configuracionempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='retefuente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
